CREATE DATABASE IF NOT EXISTS ALX_prodev;

CREATE TABLE IF NOT EXISTS user_data(
    user_id INT PRIMARY KEY, 
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    age DECIMAL NOT NULL
);