# Generated by Django 5.2.9 on 2025-12-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='Conversattion_id',
            new_name='Conversation_id',
        ),
    ]
