# Generated by Django 5.2.9 on 2025-12-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_conversattion_id_conversation_conversation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='Conversation_id',
            new_name='conversation_id',
        ),
    ]
